// <auto-generated />
using System;
using DesafioFullStackTotvs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioFullStackTotvs.Migrations
{
    [DbContext(typeof(DesafioFullStackTotvsDataContext))]
    partial class DesafioFullStackTotvsDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioFullStackTotvs.Models.Auction", b =>
                {
                    b.Property<long>("AuctionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("InitialValue");

                    b.Property<string>("Name");

                    b.Property<DateTime>("OpeningDate");

                    b.Property<DateTime>("TerminationDate");

                    b.Property<long?>("UserForeignKey");

                    b.Property<string>("UserId");

                    b.Property<string>("WasUsed");

                    b.HasKey("AuctionID");

                    b.HasIndex("UserForeignKey");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("DesafioFullStackTotvs.Models.AuctionBid", b =>
                {
                    b.Property<long>("AuctionBidID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AuctionForeignKey");

                    b.Property<string>("AuctionId");

                    b.Property<long>("BidPrice");

                    b.Property<long?>("UserForeignKey");

                    b.Property<string>("UserId");

                    b.HasKey("AuctionBidID");

                    b.HasIndex("AuctionForeignKey");

                    b.HasIndex("UserForeignKey");

                    b.ToTable("AuctionBids");
                });

            modelBuilder.Entity("DesafioFullStackTotvs.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<string>("Email");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DesafioFullStackTotvs.Models.Auction", b =>
                {
                    b.HasOne("DesafioFullStackTotvs.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserForeignKey");
                });

            modelBuilder.Entity("DesafioFullStackTotvs.Models.AuctionBid", b =>
                {
                    b.HasOne("DesafioFullStackTotvs.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionForeignKey");

                    b.HasOne("DesafioFullStackTotvs.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
